name: CheckTestsAndLint

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: npm install lodash
      - run: make lint
      - name: Coverage test
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
        with:
         coverageCommand: make test-coverage
         debug: true
